#!/bin/bash
python -m vidur.main --jsonl_trace_file config.jsonl --replica_config_device a40         --replica_config_network_device a40_pairwise_nvlink         --replica_config_model_name meta-llama/Meta-Llama-3-8B         --replica_config_tensor_parallel_size 1         --replica_config_num_pipeline_stages 1         --replica_scheduler_config_type vllm          --vllm_scheduler_config_batch_size_cap 256          --vllm_scheduler_config_max_tokens_in_batch 16384         --random_forrest_execution_time_predictor_config_prediction_max_prefill_chunk_size 16384         --random_forrest_execution_time_predictor_config_prediction_max_tokens_per_request 16384 --time_scale_factor 0.5

printf "\n\n"

python -m vidur.main --jsonl_trace_file config.jsonl --replica_config_device a40         --replica_config_network_device a40_pairwise_nvlink         --replica_config_model_name meta-llama/Meta-Llama-3-8B         --replica_config_tensor_parallel_size 1         --replica_config_num_pipeline_stages 1         --replica_scheduler_config_type vllm          --vllm_scheduler_config_batch_size_cap 256          --vllm_scheduler_config_max_tokens_in_batch 16384         --random_forrest_execution_time_predictor_config_prediction_max_prefill_chunk_size 16384         --random_forrest_execution_time_predictor_config_prediction_max_tokens_per_request 16384         --replica_config_eviction_policy lru         --replica_config_memory_size_per_pp 64GB         --replica_config_disk_size_per_pp 128GB         --replica_config_disk_cpu_thput 10GB/S         --replica_config_cpu_disk_thput 10GB/S         --replica_config_gpu_cpu_thput 16GB/S         --replica_config_cpu_gpu_thput 16GB/S         --replica_config_gpu_disk_thput 1GB/S         --replica_config_disk_gpu_thput 1GB/S         --replica_config_contention_model rw-no-contend --time_scale_factor 0.5


printf "\n\n"


python -m vidur.main --jsonl_trace_file config.jsonl --replica_config_device a40         --replica_config_network_device a40_pairwise_nvlink         --replica_config_model_name meta-llama/Meta-Llama-3-8B         --replica_config_tensor_parallel_size 1         --replica_config_num_pipeline_stages 1         --replica_scheduler_config_type vllm          --vllm_scheduler_config_batch_size_cap 256          --vllm_scheduler_config_max_tokens_in_batch 16384         --random_forrest_execution_time_predictor_config_prediction_max_prefill_chunk_size 16384         --random_forrest_execution_time_predictor_config_prediction_max_tokens_per_request 16384         --replica_config_eviction_policy lfu         --replica_config_memory_size_per_pp 64GB         --replica_config_disk_size_per_pp 128GB         --replica_config_disk_cpu_thput 10GB/S         --replica_config_cpu_disk_thput 10GB/S         --replica_config_gpu_cpu_thput 16GB/S         --replica_config_cpu_gpu_thput 16GB/S         --replica_config_gpu_disk_thput 1GB/S         --replica_config_disk_gpu_thput 1GB/S         --replica_config_contention_model rw-no-contend --time_scale_factor 0.5

printf "\n\n"

python -m vidur.main --jsonl_trace_file config.jsonl --replica_config_device a40         --replica_config_network_device a40_pairwise_nvlink         --replica_config_model_name meta-llama/Meta-Llama-3-8B         --replica_config_tensor_parallel_size 1         --replica_config_num_pipeline_stages 1         --replica_scheduler_config_type vllm          --vllm_scheduler_config_batch_size_cap 256          --vllm_scheduler_config_max_tokens_in_batch 16384         --random_forrest_execution_time_predictor_config_prediction_max_prefill_chunk_size 16384         --random_forrest_execution_time_predictor_config_prediction_max_tokens_per_request 16384         --replica_config_eviction_policy oursv1  --replica_config_ours_v1_token_thres 5000 --replica_config_compress 0.5-0.8-0.0-0.0        --replica_config_memory_size_per_pp 64GB         --replica_config_disk_size_per_pp 128GB         --replica_config_disk_cpu_thput 10GB/S         --replica_config_cpu_disk_thput 10GB/S         --replica_config_gpu_cpu_thput 16GB/S         --replica_config_cpu_gpu_thput 16GB/S         --replica_config_gpu_disk_thput 1GB/S         --replica_config_disk_gpu_thput 1GB/S         --replica_config_contention_model rw-no-contend --time_scale_factor 0.5
