#!/bin/bash
alphas="0.08 0.5 10.0 50.0 108.0 1000.0 5000.0"
traces="c1.jsonl"
for trace in $traces; do
    echo "Running trace $trace"
    for alpha in $alphas; do
        echo "Running alpha $alpha"
        python3 -m vidur.main --jsonl_trace_file "$trace" --replica_config_device a40 --replica_config_network_device a40_pairwise_nvlink --replica_config_model_name meta-llama/Meta-Llama-3-8B --replica_config_tensor_parallel_size 1 --replica_config_num_pipeline_stages 1 --replica_scheduler_config_type vllm --vllm_scheduler_config_batch_size_cap 256 --vllm_scheduler_config_max_tokens_in_batch 16384 --random_forrest_execution_time_predictor_config_prediction_max_prefill_chunk_size 16384 --random_forrest_execution_time_predictor_config_prediction_max_tokens_per_request 16384 --replica_config_eviction_policy oursframework  --replica_config_evictor_alpha "$alpha" --replica_config_compress 0.5-0.995-0.0-0.0,0.1-0.95-0.0-0.0,0.05-0.9-0.0-0.0,0.02-0.8-0.0-0.0 --replica_config_memory_size_per_pp 128GB --replica_config_disk_size_per_pp 2048GB --replica_config_disk_cpu_thput 10GB/S --replica_config_cpu_disk_thput 10GB/S --replica_config_gpu_cpu_thput 16GB/S --replica_config_cpu_gpu_thput 16GB/S --replica_config_gpu_disk_thput 1GB/S --replica_config_disk_gpu_thput 1GB/S --replica_config_contention_model rw-no-contend --no-metrics_config_write_metrics --time_scale_factor 0.5 | python3 extract.py
        printf "\n\n"
    done
    echo 'Running static 0.5'
    python3 -m vidur.main --jsonl_trace_file "$trace" --replica_config_device a40 --replica_config_network_device a40_pairwise_nvlink --replica_config_model_name meta-llama/Meta-Llama-3-8B --replica_config_tensor_parallel_size 1 --replica_config_num_pipeline_stages 1 --replica_scheduler_config_type vllm --vllm_scheduler_config_batch_size_cap 256 --vllm_scheduler_config_max_tokens_in_batch 16384 --random_forrest_execution_time_predictor_config_prediction_max_prefill_chunk_size 16384 --random_forrest_execution_time_predictor_config_prediction_max_tokens_per_request 16384 --replica_config_eviction_policy oursframework  --replica_config_evictor_alpha 5000.0 --replica_config_compress 0.5-0.995-0.0-0.0 --replica_config_memory_size_per_pp 128GB --replica_config_disk_size_per_pp 2048GB --replica_config_disk_cpu_thput 10GB/S --replica_config_cpu_disk_thput 10GB/S --replica_config_gpu_cpu_thput 16GB/S --replica_config_cpu_gpu_thput 16GB/S --replica_config_gpu_disk_thput 1GB/S --replica_config_disk_gpu_thput 1GB/S --replica_config_contention_model rw-no-contend --no-metrics_config_write_metrics --time_scale_factor 0.5 | python3 extract.py
    printf "\n\n"
    echo 'Running static 0.1'
    python3 -m vidur.main --jsonl_trace_file "$trace" --replica_config_device a40 --replica_config_network_device a40_pairwise_nvlink --replica_config_model_name meta-llama/Meta-Llama-3-8B --replica_config_tensor_parallel_size 1 --replica_config_num_pipeline_stages 1 --replica_scheduler_config_type vllm --vllm_scheduler_config_batch_size_cap 256 --vllm_scheduler_config_max_tokens_in_batch 16384 --random_forrest_execution_time_predictor_config_prediction_max_prefill_chunk_size 16384 --random_forrest_execution_time_predictor_config_prediction_max_tokens_per_request 16384 --replica_config_eviction_policy oursframework  --replica_config_evictor_alpha 5000.0 --replica_config_compress 0.1-0.95-0.0-0.0 --replica_config_memory_size_per_pp 128GB --replica_config_disk_size_per_pp 2048GB --replica_config_disk_cpu_thput 10GB/S --replica_config_cpu_disk_thput 10GB/S --replica_config_gpu_cpu_thput 16GB/S --replica_config_cpu_gpu_thput 16GB/S --replica_config_gpu_disk_thput 1GB/S --replica_config_disk_gpu_thput 1GB/S --replica_config_contention_model rw-no-contend --no-metrics_config_write_metrics --time_scale_factor 0.5 | python3 extract.py
    printf "\n\n"
    echo 'Running static 0.05'
    python3 -m vidur.main --jsonl_trace_file "$trace" --replica_config_device a40 --replica_config_network_device a40_pairwise_nvlink --replica_config_model_name meta-llama/Meta-Llama-3-8B --replica_config_tensor_parallel_size 1 --replica_config_num_pipeline_stages 1 --replica_scheduler_config_type vllm --vllm_scheduler_config_batch_size_cap 256 --vllm_scheduler_config_max_tokens_in_batch 16384 --random_forrest_execution_time_predictor_config_prediction_max_prefill_chunk_size 16384 --random_forrest_execution_time_predictor_config_prediction_max_tokens_per_request 16384 --replica_config_eviction_policy oursframework  --replica_config_evictor_alpha 5000.0 --replica_config_compress 0.05-0.9-0.0-0.0 --replica_config_memory_size_per_pp 128GB --replica_config_disk_size_per_pp 2048GB --replica_config_disk_cpu_thput 10GB/S --replica_config_cpu_disk_thput 10GB/S --replica_config_gpu_cpu_thput 16GB/S --replica_config_cpu_gpu_thput 16GB/S --replica_config_gpu_disk_thput 1GB/S --replica_config_disk_gpu_thput 1GB/S --replica_config_contention_model rw-no-contend --no-metrics_config_write_metrics --time_scale_factor 0.5 | python3 extract.py
    printf "\n\n"
    echo 'Running static 0.02'
    python3 -m vidur.main --jsonl_trace_file "$trace" --replica_config_device a40 --replica_config_network_device a40_pairwise_nvlink --replica_config_model_name meta-llama/Meta-Llama-3-8B --replica_config_tensor_parallel_size 1 --replica_config_num_pipeline_stages 1 --replica_scheduler_config_type vllm --vllm_scheduler_config_batch_size_cap 256 --vllm_scheduler_config_max_tokens_in_batch 16384 --random_forrest_execution_time_predictor_config_prediction_max_prefill_chunk_size 16384 --random_forrest_execution_time_predictor_config_prediction_max_tokens_per_request 16384 --replica_config_eviction_policy oursframework  --replica_config_evictor_alpha 5000.0 --replica_config_compress 0.02-0.8-0.0-0.0 --replica_config_memory_size_per_pp 128GB --replica_config_disk_size_per_pp 2048GB --replica_config_disk_cpu_thput 10GB/S --replica_config_cpu_disk_thput 10GB/S --replica_config_gpu_cpu_thput 16GB/S --replica_config_cpu_gpu_thput 16GB/S --replica_config_gpu_disk_thput 1GB/S --replica_config_disk_gpu_thput 1GB/S --replica_config_contention_model rw-no-contend --no-metrics_config_write_metrics --time_scale_factor 0.5 | python3 extract.py
    printf "\n\n"
done
